[package]
name = "grasql"
version = "0.1.0"
edition = "2021"

[lib]
name = "grasql"
crate-type = ["cdylib"]

[dependencies]
graphql-query = "1.0.0"
rustler = "0.36.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
